### ISSUE TITLE
Error thrown when calling OOTB mail action

### ISSUE THREAD

**Issue by idwright** [malariagen/alfresco-discussions#5]
e.g. from javascript console

    // create mail action
    var mail = actions.create("mail");
    mail.parameters.to = "test@example.org";   
    mail.parameters.subject="Test mail action";

    mail.parameters.body = "Test body";
 
    //execute action against a document
    mail.execute(document);

```
java.lang.RuntimeException: Don't know where to route call to method public abstract org.alfresco.service.cmr.action.ActionDefinition org.alfresco.repo.action.executer.ActionExecuter.getActionDefinition()
	at org.alfresco.repo.management.subsystems.SubsystemProxyFactory.locateBean(SubsystemProxyFactory.java:217)
	at org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy325.getActionDefinition(Unknown Source)
	at org.alfresco.repo.action.ActionServiceImpl.getActionDefinition(ActionServiceImpl.java:283)
```

**Comment by idwright** [comment]
Logged an issue https://issues.alfresco.com/jira/browse/ALF-21838
